name: resource

on: [pull_request, push, workflow_dispatch]

jobs:
  resource:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Run check.sh
      working-directory: .github/scripts
      run: ./check.sh ../../homework/resourceD/valgrind-output.txt
  valgrind:
    runs-on: ubuntu-latest
    env:
      path: homework/resourceD/build
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install valgrind
      run: sudo apt install -y valgrind
    - name: Create build directory
      run: mkdir ${{ env.path }}
    - name: Compile
      working-directory: ${{ env.path }}
      run: |
        cmake ..
        make -j
    - name: Run valgrind
      working-directory: ${{ env.path }}
      run: valgrind ./resourceD d
